version: '3.5'
networks:
  my-network:
    driver: bridge
services:
  db:
    image: postgres:14
    container_name: pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - my-network

  nodejs:
    build:
      context: ./
    container_name: node
    environment:
      - DB_URL=postgres://postgres:postgres@pg:5432/test_db
      - email=ubademy.14@gmail.com
      - pswd=Brancahdp123
      - DD_ENV=local
      - DD_LOGS_INJECTION=true
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
  dd:
    image: datadog/agent:latest
    container_name: datadog-agent
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126/tcp"
    networks:
      - my-network
