version: '3'
services:
  db:
    image: postgres:14
    container_name: postgre
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

  nodejs:
    build:
      context: ./
    container_name: node
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/test_db
    ports:
      - "8080:8080"
    depends_on:
      - db
